name: Run Tests with Database

on:
  push:
    branches: [ master ] # Or your default branch name
  pull_request:
    branches: [ master ] # Or your default branch name

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `docker compose`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432 # Use the standard PostgreSQL port

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
      env:
        # The hostname `postgres` matches the service label above
        DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
        # Add any other environment variables your tests might need
